version: '2'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:3.2-alpine
    ports:
      - 6379:6379

  smtp:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
