# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkyouapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, upload_to=b'uploads/img/collections')),
                ('private', models.BooleanField(default=False)),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
                ('user_it_belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='link',
            old_name='name',
            new_name='text',
        ),
        migrations.AddField(
            model_name='link',
            name='order_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='collection_it_belongs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='linkyouapp.Collection'),
            preserve_default=False,
        ),
    ]
