# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('linkyouapp', '0002_auto_20170222_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='icon',
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='link',
            name='orderId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
